#########################################################################
# Title:            Saltbox: Deluge                                     #
# Author(s):        salty                                               #
# URL:              https://github.com/saltyorg/Saltbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Assign ports
  port_assignment:
    base_path: "{{ server_appdata_path }}"
    namespace: deluge
    owner: "{{ deluge_name }}"
    claims:
      peer:
        low_bound: "{{ lookup('role_var', '_port_peer_low_bound', role='deluge') }}"
        high_bound: "{{ lookup('role_var', '_port_peer_high_bound', role='deluge') }}"
        protocols: ["tcp", "udp"]
  register: deluge_port_assignment

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Pre-Install Tasks
  ansible.builtin.include_tasks: "subtasks/pre-install/main.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Install Tasks
  ansible.builtin.include_tasks: "subtasks/post-install/main.yml"
