#########################################################################
# Title:         Pre-Tasks: Variables Tasks                             #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Find Saltbox role defaults
  ansible.builtin.find:
    paths: "/srv/git/saltbox/roles"
    file_type: directory
    patterns: "defaults"
    recurse: true
  register: pre_tasks_saltbox_roles

- name: Include Saltbox role default vars
  ansible.builtin.include_vars: "{{ item }}/main.yml"
  with_items: "{{ pre_tasks_saltbox_roles.files | map(attribute='path') | sort }}"

- name: Sandbox
  when: (playbook_dir == pre_tasks_saltbox_mod_location)
  block:
    - name: Find Sandbox role defaults
      ansible.builtin.find:
        paths: "{{ server_appdata_path }}/sandbox/roles"
        file_type: directory
        patterns: "defaults"
        recurse: true
      register: pre_tasks_sandbox_roles

    - name: Include Sandbox role default vars
      ansible.builtin.include_vars: "{{ item }}/main.yml"
      with_items: "{{ pre_tasks_sandbox_roles.files | map(attribute='path') | sort }}"

- name: Check if 'localhost.yml' exists
  ansible.builtin.stat:
    path: "/srv/git/saltbox/inventories/host_vars/localhost.yml"
  register: localhost_inventory_file

- name: Import Inventory variables
  ansible.builtin.include_vars: "/srv/git/saltbox/inventories/host_vars/localhost.yml"
  when: localhost_inventory_file.stat.exists
