ignored_tags:
  - "arr-db"
  - "authelia-reset"
  - "authentik-reset"
  - "btrfsmaintenance"
  - "cloudflare"
  - "cloudplow"
  - "cloudplow-disable"
  - "cloudplow-reset"
  - "common"
  - "crowdsec"
  - "ddns"
  - "docker"
  - "docker-filesystem-resize"
  - "download-clients"
  - "download-indexers"
  - "hetzner"
  - "kernel"
  - "lldap-reset"
  - "media-server"
  - "motd"
  - "motd-generate-config"
  - "mounts"
  - "nvidia"
  - "nvidia-purge"
  - "plex-db"
  - "plex-reclaim"
  - "plex-reset-codecs"
  - "postgres-host"
  - "preinstall"
  - "python"
  - "rclone"
  - "roles"
  - "scripts"
  - "shell"
  - "system"
  - "traefik"
  - "traefik-reset-certs"
  - "user"
