#########################################################################
# Title:         Saltbox: Nvidia | Patch Tasks                          #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Patch | Verify selected version is supported
  ansible.builtin.command:
    argv:
      - /bin/bash
      - "{{ nvidia_patch_download_dest }}"
      - -c
      - "{{ nvidia_driver_resolution.resolved_version }}"
  changed_when: false

- name: Patch | Apply Nvidia encode patch
  ansible.builtin.command:
    argv:
      - /bin/bash
      - "{{ nvidia_patch_download_dest }}"
      - -d
      - "{{ nvidia_driver_resolution.resolved_version }}"
  register: nvidia_patch_install
  changed_when: "'Patched!' in nvidia_patch_install.stdout"

- name: Patch | Verify Nvidia patch backup
  ansible.builtin.find:
    paths: "{{ nvidia_patch_backup_file_location }}"
    patterns: "libnvidia-encode.so.{{ nvidia_driver_resolution.resolved_version }}"
    file_type: file
  register: nvidia_patch_backup
  failed_when: nvidia_patch_backup.matched != 1
