#########################################################################
# Title:         Saltbox: Plex Extra Tasks Role                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Gather Plex Docker container information
  community.docker.docker_container_info:
    name: "{{ lookup('role_var', '_docker_container', role='plex') }}"
  register: plex_extra_tasks_container_info

- name: "Continue when Plex Docker container exists"
  ansible.builtin.include_tasks: "main2.yml"
  when: plex_extra_tasks_container_info.exists
