#########################################################################
# Title:         Saltbox: Mount Templates Role                          #
# Author(s):     owine                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create mount-templates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true
  with_items:
    - "{{ server_appdata_path }}/mount-templates"

- name: Clone mount-templates repo 'HEAD'
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/clone_git_repo.yml"
  vars:
    git_repo_url: https://github.com/saltyorg/mount-templates.git
    git_repo_dest: "{{ server_appdata_path }}/mount-templates"
    git_repo_version: HEAD
    git_repo_force: true
    git_repo_become: true
    git_repo_become_user: "{{ user.name }}"
    git_repo_result_var: mount_templates_clone_status
    git_repo_fail_on_error: false

- name: Clone mount-templates repo 'main'
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/clone_git_repo.yml"
  vars:
    git_repo_url: https://github.com/saltyorg/mount-templates.git
    git_repo_dest: "{{ server_appdata_path }}/mount-templates"
    git_repo_version: main
    git_repo_force: true
    git_repo_become: true
    git_repo_become_user: "{{ user.name }}"
  when: mount_templates_clone_status is failed
