#########################################################################
# Title:         Saltbox: System | CPU Frequency Tasks                  #
# Author(s):     l3uddz, EnorMOZ, desimaniac, salty                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: CPU Frequency | Install 'cpufrequtils'
  ansible.builtin.apt:
    name: cpufrequtils
    state: latest

- name: CPU Frequency | Install 'linux-tools' for Ubuntu
  ansible.builtin.apt:
    state: latest
    name:
      - linux-tools-common
      - linux-tools-generic
  when: (ansible_facts['distribution'] == 'Ubuntu')

- name: "CPU Frequency | Install 'linux-tools-{{ ansible_facts['kernel'] }}'"
  ansible.builtin.apt:
    name: "linux-tools-{{ ansible_facts['kernel'] }}"
    state: latest
  ignore_errors: true

- name: CPU Frequency | Ensure 'cpufrequtils' is enabled
  community.general.ini_file:
    path: "/etc/default/cpufrequtils"
    section: null
    option: 'ENABLE'
    value: '"true"'
    state: present
    create: true
    mode: "0644"
    no_extra_spaces: true

- name: CPU Frequency | Set 'GOVERNOR' used on boot to performance
  community.general.ini_file:
    path: "/etc/default/cpufrequtils"
    section: null
    option: 'GOVERNOR'
    value: '"performance"'
    state: present
    create: true
    mode: "0644"
    no_extra_spaces: true

- name: CPU Frequency | Remove misspelled 'GOVENOR' entry
  community.general.ini_file:
    path: "/etc/default/cpufrequtils"
    section: null
    option: 'GOVENOR'
    mode: "0644"
    state: absent

- name: CPU Frequency | Set 'GOVERNOR' used currently to performance
  block:
    - name: CPU Frequency | Find scaling governor files
      ansible.builtin.find:
        paths: /sys/devices/system/cpu
        patterns: scaling_governor
        file_type: file
        recurse: true
      register: cpu_scaling_governor_files

    - name: CPU Frequency | Write performance governor
      ansible.builtin.command:
        argv:
          - "tee"
          - "{{ item.path }}"
        stdin: performance
      loop: "{{ cpu_scaling_governor_files.files }}"
      failed_when: false

- name: CPU Frequency | Populate Service Facts
  ansible.builtin.service_facts:

- name: CPU Frequency | Stop and disable 'ondemand.service'
  ansible.builtin.systemd_service:
    name: ondemand
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true
  when: ('ondemand.service' in ansible_facts['services'] and ansible_facts['services']['ondemand.service']['status'] == 'enabled')
