#########################################################################
# Title:         Saltbox: Shell | Misc                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Misc | Install argcomplete
  ansible.builtin.command:
    argv:
      - "/usr/bin/pip"
      - "install"
      - "{{ shell_misc_argcomplete_pip_package }}"
  when: ansible_facts['distribution_version'] is version('22.04', '<=')

- name: Misc | Install argcomplete
  ansible.builtin.apt:
    name: python3-argcomplete
    state: present
  when: ansible_facts['distribution_version'] is version('24.04', '>=')

# For Ansible command line utilities
- name: Misc | Activate argcomplete
  ansible.builtin.command:
    argv: "{{ shell_misc_argcomplete_command_args
              | saltbox_argv('shell_misc_argcomplete_command_args') }}"
    expand_argument_vars: false
