#########################################################################
# Title:         Saltbox: Shell | z (jump around)                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: z | Create 'z' directories
  ansible.builtin.file:
    path: "{{ shell_z_git_repo_dest }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true

- name: z | Clone 'z' repo
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/clone_git_repo.yml"
  vars:
    git_repo_url: "{{ shell_z_git_repo_url }}"
    git_repo_dest: "{{ shell_z_git_repo_dest }}"
    git_repo_version: HEAD
    git_repo_force: true
    git_repo_become: true
    git_repo_become_user: "{{ user.name }}"
