############################################################################################
# Title:         Saltbox: Resources | Tasks | systemd | Start PostgreSQL Host after Backup #
# Author(s):     salty                                                                     #
# URL:           https://github.com/saltyorg/Saltbox                                       #
# --                                                                                       #
############################################################################################
#                   GNU General Public License v3.0                                        #
############################################################################################
---
- name: Resources | Tasks | systemd | Start PostgreSQL Host after Backup | Restore running services
  when: postgres_host_backup_services_running | default([]) | length > 0
  block:
    - name: Resources | Tasks | systemd | Start PostgreSQL Host after Backup | Start services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
      loop: "{{ postgres_host_backup_services_running }}"

    - name: Resources | Tasks | systemd | Start PostgreSQL Host after Backup | Populate service facts
      ansible.builtin.service_facts:

    - name: Resources | Tasks | systemd | Start PostgreSQL Host after Backup | Assert services are running
      ansible.builtin.assert:
        that:
          - (ansible_facts['services'][item] is defined) and (ansible_facts['services'][item]['state'] == 'running')
        fail_msg: "PostgreSQL host service '{{ item }}' did not return to its pre-backup running state."
      loop: "{{ postgres_host_backup_services_running }}"
