#########################################################################
# Title:         Saltbox: Docker | DNS Tasks                            #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "DNS | Cleanup 'docker-update-hosts.service'"
  ansible.builtin.systemd_service:
    name: docker-update-hosts
    state: stopped
    enabled: false
  when: (ansible_facts['services']['docker-update-hosts.service'] is defined)

- name: "DNS | Remove docker-update-hosts.service"
  ansible.builtin.file:
    path: /etc/systemd/system/docker-update-hosts.service
    state: absent

- name: "DNS | Get latest sdhm release metadata"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/git/github_api_request.yml"
  vars:
    github_api_url: "{{ docker_dns_releases_url }}"
    github_api_result_var: docker_dns_release_api

- name: "DNS | Resolve sdhm download URL"
  ansible.builtin.set_fact:
    docker_dns_download_url: "{{ ((docker_dns_release_api.content | from_json).assets
                                 | selectattr('name', 'equalto', 'sdhm_linux_amd64')
                                 | map(attribute='browser_download_url')
                                 | first) }}"
  changed_when: false

- name: "DNS | Download sdhm"
  ansible.builtin.get_url:
    url: "{{ docker_dns_download_url }}"
    dest: "{{ docker_dns_binary_path }}"
    owner: "root"
    group: "root"
    mode: "0755"
  register: x
  until: "x is not failed"
  retries: "{{ ansible_retry_count
            if (not continuous_integration)
            else ansible_retry_count_ci }}"
  delay: 10

- name: "DNS | Get sdhm binary version"
  ansible.builtin.shell: "{{ docker_dns_binary_path }} --version | awk '{ print $3 }'"
  register: sdhm_binary_version
  changed_when: false

- name: "DNS | Display sdhm binary version"
  ansible.builtin.debug:
    msg: "sdhm {{ sdhm_binary_version.stdout }} installed."

- name: "DNS | Get next available port within the range of '8190-8180'"
  find_open_port:
    low_bound: "8190"
    high_bound: "8280"
    protocol: both
  register: port_lookup_8190

- name: "DNS | Import 'saltbox_managed_docker_update_hosts.service'"
  ansible.builtin.template:
    src: docker-update-hosts.service.j2
    dest: /etc/systemd/system/saltbox_managed_docker_update_hosts.service
    mode: "0644"
    force: true

- name: "DNS | Start 'saltbox_managed_docker_update_hosts.service'"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/systemd/manage_service.yml"
  vars:
    _service_name: saltbox_managed_docker_update_hosts
    _service_state: restarted
    _service_enabled: true
    _service_daemon_reload: true
    _service_reenable: true
