#########################################################################
# Title:         Saltbox: Docker | DNS Tasks                            #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "DNS | Cleanup 'docker-update-hosts.service'"
  ansible.builtin.systemd_service:
    name: docker-update-hosts
    state: stopped
    enabled: false
  when: (ansible_facts['services']['docker-update-hosts.service'] is defined)

- name: "DNS | Remove docker-update-hosts.service"
  ansible.builtin.file:
    path: /etc/systemd/system/docker-update-hosts.service
    state: absent

- name: "DNS | Install sdhm release"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/subtasks/github_binary/install.yml"
  vars:
    docker_github_binary_install:
      name: sdhm
      path: "{{ docker_dns_binary_path }}"
      download_url: "{{ docker_dns_download_url }}"
      checksum: "{{ docker_dns_release_checksum }}"
      update_required: "{{ docker_dns_update_required }}"

- name: "DNS | Stop existing managed service"
  ansible.builtin.systemd_service:
    name: saltbox_managed_docker_update_hosts
    state: stopped
  when: ansible_facts['services']['saltbox_managed_docker_update_hosts.service'] is defined

- name: "DNS | Assign health port"
  port_assignment:
    base_path: "{{ server_appdata_path }}"
    namespace: docker
    owner: docker-dns
    claims:
      health:
        low_bound: "{{ docker_dns_port_low_bound }}"
        high_bound: "{{ docker_dns_port_high_bound }}"
        protocols: ["tcp"]
  register: docker_dns_port_assignment

- name: "DNS | Import 'saltbox_managed_docker_update_hosts.service'"
  ansible.builtin.template:
    src: docker-update-hosts.service.j2
    dest: /etc/systemd/system/saltbox_managed_docker_update_hosts.service
    mode: "0644"
    force: true

- name: "DNS | Start 'saltbox_managed_docker_update_hosts.service'"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/systemd/manage_service.yml"
  vars:
    _service_name: saltbox_managed_docker_update_hosts
    _service_state: started
    _service_enabled: true
    _service_daemon_reload: true
    _service_reenable: true
