#########################################################################
# Title:         Saltbox: Docker | Housekeeping Tasks                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Housekeeping | Remove all unused docker images"
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
  ignore_errors: true

- name: "Housekeeping | Remove all unused docker volumes"
  community.docker.docker_prune:
    volumes: true
  ignore_errors: true
