#########################################################################
# Title:         Saltbox: Docker | Network Tasks                        #
# Author(s):     desimaniac, l3uddz, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Network | Inspect saltbox docker network"
  community.docker.docker_network_info:
    name: saltbox
  register: docker_saltbox_network
  until: "docker_saltbox_network is not failed"
  retries: 10
  delay: 10

- name: "Network | Inspect bridge docker network"
  community.docker.docker_network_info:
    name: bridge
  register: docker_bridge_network

- name: "Network | Get containers configured for saltbox network"
  community.docker.docker_host_info:
    containers: true
    containers_all: true
    containers_filters:
      network: saltbox
  register: docker_saltbox_containers
  when: docker_saltbox_network.exists

- name: "Network (IPv6) | Create new IPv6 saltbox docker network block"
  when: (not docker_saltbox_network.exists) and docker_ipv6
  block:
    - name: "Network (IPv6) | Create saltbox network"
      community.docker.docker_network:
        name: saltbox
        state: present
        enable_ipv6: true
        ipam_config:
          - subnet: 172.19.0.0/16
          - subnet: fd00:dead:beef::/48

- name: "Network (IPv4) | Create new IPv4 saltbox docker network block"
  when: (not docker_saltbox_network.exists) and (not docker_ipv6)
  block:
    - name: "Network (IPv4) | Create saltbox network"
      community.docker.docker_network:
        name: saltbox
        state: present
        enable_ipv6: false
        ipam_config:
          - subnet: 172.19.0.0/16

- name: "Network (IPv6) | Migrating existing saltbox docker network block to IPv6"
  when: docker_saltbox_network.exists and (not docker_saltbox_network.network.EnableIPv6) and docker_ipv6
  block:
    - name: "Network (IPv6) | Inspect containers for aliases"
      community.docker.docker_container_info:
        name: "{{ docker_network_container.Id }}"
      register: docker_ipv6_container_info
      loop: "{{ docker_saltbox_containers.containers }}"
      loop_control:
        loop_var: docker_network_container
        label: "{{ docker_network_container.Names | first | regex_replace('^/', '') }}"

    - name: "Network (IPv6) | Disconnect containers from bridge network"
      community.docker.docker_network:
        name: bridge
        connected: >-
          {{
            (docker_bridge_network.network.Containers | default({}) | dict2items
             | map(attribute='value.Name') | list)
            | difference(
                docker_saltbox_containers.containers
                | map(attribute='Names') | map('first')
                | map('regex_replace', '^/', '') | list
            )
          }}
      register: disconnect_containers
      ignore_errors: true
      when: docker_bridge_network.exists

    - name: "Network (IPv6) | Remove saltbox network"
      community.docker.docker_network:
        name: saltbox
        state: absent

    - name: "Network (IPv6) | Create saltbox network"
      community.docker.docker_network:
        name: saltbox
        state: present
        enable_ipv6: true
        ipam_config:
          - subnet: 172.19.0.0/16
          - subnet: fd00:dead:beef::/48

    - name: "Network (IPv6) | Connect containers to saltbox network"
      ansible.builtin.command:
        argv: "{{ ['docker', 'network', 'connect']
                  + (([docker_network_container.container.Name | regex_replace('^/', '')]
                      | union(docker_network_container.container.NetworkSettings.Networks.saltbox.Aliases
                              | default([], true)))
                     | map('regex_replace', '^', '--alias=')
                     | list)
                  + ['saltbox', docker_network_container.container.Name | regex_replace('^/', '')] }}"
      loop: >-
        {{
          docker_ipv6_container_info.results
          | selectattr('container', 'defined')
          | rejectattr('container', 'none')
          | list
        }}
      loop_control:
        loop_var: docker_network_container
        label: "{{ docker_network_container.container.Name | regex_replace('^/', '') }}"
      register: connect_containers
      failed_when: connect_containers.rc > 1
      ignore_errors: true

- name: "Network (IPv4) | Migrating existing saltbox docker network block to IPv4"
  when: docker_saltbox_network.exists and docker_saltbox_network.network.EnableIPv6 and (not docker_ipv6)
  block:
    - name: "Network (IPv4) | Inspect containers for aliases"
      community.docker.docker_container_info:
        name: "{{ docker_network_container.Id }}"
      register: docker_ipv4_container_info
      loop: "{{ docker_saltbox_containers.containers }}"
      loop_control:
        loop_var: docker_network_container
        label: "{{ docker_network_container.Names | first | regex_replace('^/', '') }}"

    - name: "Network (IPv4) | Disconnect containers from bridge network"
      community.docker.docker_network:
        name: bridge
        connected: >-
          {{
            (docker_bridge_network.network.Containers | default({}) | dict2items
             | map(attribute='value.Name') | list)
            | difference(
                docker_saltbox_containers.containers
                | map(attribute='Names') | map('first')
                | map('regex_replace', '^/', '') | list
            )
          }}
      register: disconnect_containers
      ignore_errors: true
      when: docker_bridge_network.exists

    - name: "Network (IPv4) | Remove saltbox network"
      community.docker.docker_network:
        name: saltbox
        state: absent

    - name: "Network (IPv4) | Create saltbox network"
      community.docker.docker_network:
        name: saltbox
        state: present
        enable_ipv6: false
        ipam_config:
          - subnet: 172.19.0.0/16

    - name: "Network (IPv4) | Connect containers to saltbox network"
      ansible.builtin.command:
        argv: "{{ ['docker', 'network', 'connect']
                  + (([docker_network_container.container.Name | regex_replace('^/', '')]
                      | union(docker_network_container.container.NetworkSettings.Networks.saltbox.Aliases
                              | default([], true)))
                     | map('regex_replace', '^', '--alias=')
                     | list)
                  + ['saltbox', docker_network_container.container.Name | regex_replace('^/', '')] }}"
      loop: >-
        {{
          docker_ipv4_container_info.results
          | selectattr('container', 'defined')
          | rejectattr('container', 'none')
          | list
        }}
      loop_control:
        loop_var: docker_network_container
        label: "{{ docker_network_container.container.Name | regex_replace('^/', '') }}"
      register: connect_containers
      failed_when: connect_containers.rc > 1
      ignore_errors: true

- name: "Network | Remove IPv6 NAT Container (Legacy)"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    container_name: "ipv6nat"

- name: "Network | Unset variables"
  ansible.builtin.set_fact:
    docker_saltbox_network:
    docker_bridge_network:
    docker_saltbox_containers:
    docker_ipv6_container_info:
    docker_ipv4_container_info:
