#########################################################################
# Title:         Saltbox: Docker | Nvidia Tasks                         #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Nvidia | Remove old repository list
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/nvidia-container-toolkit.list"
    - "/etc/apt/sources.list.d/nvidia-container-runtime.list"

- name: Nvidia | Add 'nvidia-container-toolkit' APT Repo Key
  ansible.builtin.get_url:
    url: "{{ nvidia_docker_runtime_apt_key_url }}"
    dest: /etc/apt/keyrings/nvidia.asc
    mode: "0644"
    force: true
  register: result
  retries: "{{ ansible_retry_count
            if (not continuous_integration)
            else ansible_retry_count_ci }}"
  delay: 10
  until: result is succeeded

- name: Nvidia | Add 'nvidia-container-toolkit' APT list
  ansible.builtin.deb822_repository:
    name: "{{ nvidia_docker_runtime_apt_repo_file }}"
    types:
      - deb
    uris: "{{ nvidia_docker_apt_repo_uris }}"
    suites: "{{ nvidia_docker_apt_repo_suites }}"
    signed_by: "{{ nvidia_docker_apt_repo_signed_by }}"
    state: present
    mode: "0644"
  register: nvidia_docker_apt_repository_result

- name: Nvidia | Update APT package index after repository change
  ansible.builtin.apt:
    update_cache: true
  when: (nvidia_docker_apt_repository_result is changed)

- name: Nvidia | Remove 'nvidia-container-runtime'
  ansible.builtin.apt:
    name: "nvidia-container-runtime"
    state: absent

- name: Nvidia | Install 'nvidia-container-toolkit'
  ansible.builtin.apt:
    name: "nvidia-container-toolkit"
    update_cache: true
    state: latest

- name: Nvidia | Validate container toolkit GPU discovery
  ansible.builtin.command: "nvidia-container-cli info"
  register: nvidia_container_toolkit_validation
  changed_when: false
