#########################################################################
# Title:         Saltbox: Rclone - Install Binary Tasks                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install Binary | Install common packages
  ansible.builtin.apt:
    state: latest
    name:
      - unzip
      - man-db

- name: Install Binary | Create rclone directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true
  with_items:
    - "/home/{{ user.name }}/.config"
    - "/home/{{ user.name }}/.config/rclone"

- name: Install Binary | Find stale rclone tmp paths
  ansible.builtin.find:
    paths: /tmp
    patterns: rclone-*-linux-amd64
    file_type: any
    recurse: false
  register: stale_rclone_tmp_paths

- name: Install Binary | Cleanup stale rclone tmp paths
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ stale_rclone_tmp_paths.files }}"

- name: Install Binary | Display rclone version being installed
  ansible.builtin.debug:
    msg: "Installing Rclone version: {{ rclone_version_specified }}"
  when: rclone_version_is_specified

- name: "Install Binary | Download and unarchive rclone"
  block:
    - name: "Install Binary | Download and unarchive rclone"
      ansible.builtin.unarchive:
        src: "{{ rclone_download_url }}"
        dest: /tmp
        copy: false
        validate_certs: false
      register: x
      until: "x is not failed"
      retries: "{{ ansible_retry_count
                if (not continuous_integration)
                else ansible_retry_count_ci }}"
      delay: 10
      timeout: 60

  rescue:
    - name: "Install Binary | Download and unarchive rclone from Github"
      ansible.builtin.unarchive:
        src: "{{ rclone_latest_download_url }}"
        dest: /tmp
        copy: false
        validate_certs: false
      register: x
      until: "x is not failed"
      retries: "{{ ansible_retry_count
                if (not continuous_integration)
                else ansible_retry_count_ci }}"
      delay: 10
      timeout: 60

- name: Install Binary | Find rclone tmp dir
  ansible.builtin.find:
    paths: /tmp
    patterns: rclone-*-linux-amd64
    file_type: directory
    recurse: false
  register: rclone_tmp_dirs

- name: Install Binary | Validate rclone tmp dir
  ansible.builtin.assert:
    that:
      - rclone_tmp_dirs.matched == 1

- name: Install Binary | Copy binary to /usr/bin/rclone
  ansible.builtin.copy:
    src: "{{ rclone_tmp_dirs.files[0].path }}/rclone"
    dest: "/usr/bin/rclone"
    mode: "0775"
    owner: root
    group: root
    force: true

- name: Install Binary | Make dir for local manpages
  ansible.builtin.file:
    path: '/usr/local/share/man/man1'
    state: directory
    mode: "0775"
    owner: root
    group: root

- name: Install Binary | Copy manpage
  ansible.builtin.copy:
    src: "{{ rclone_tmp_dirs.files[0].path }}/rclone.1"
    dest: /usr/local/share/man/man1/rclone.1
    mode: "0664"
    owner: root
    group: root

- name: Install Binary | Install manpage
  ansible.builtin.command:
    argv:
      - "mandb"
  changed_when: false

- name: Install Binary | Get rclone version
  ansible.builtin.command:
    argv:
      - "rclone"
      - "--version"
  register: rclone_version_command
  ignore_errors: true
  changed_when: false

- name: Install Binary | Parse rclone version
  ansible.builtin.set_fact:
    rclone_version: "{{ (rclone_version_command.stdout_lines | first | default('')).split()[1]
                        | default('')
                        | regex_replace('^v', '') }}"

- name: "Install Binary | Display rclone version"
  ansible.builtin.debug:
    msg: "Rclone version {{ rclone_version }} installed."
