#########################################################################
# Title:         Saltbox: Docker | Binary Tasks 2                       #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Check '{{ lookup('vars', item ~ '_name') }}' package status
  ansible.builtin.include_tasks: "package_status.yml"

- name: Binary | Converge '{{ lookup('vars', item ~ '_name') }}'
  block:
    - name: Binary | Release '{{ docker_binary_dpkg_name }}' from hold
      ansible.builtin.dpkg_selections:
        name: "{{ docker_binary_dpkg_name }}"
        selection: install
      when:
        - docker_binary_currently_held
        - docker_binary_version_change_required or (not put_docker_dpkg_into_hold)

    - name: Binary | Install '{{ docker_binary_dpkg_name }}={{ docker_binary_target_version }}'
      ansible.builtin.apt:
        name: "{{ docker_binary_dpkg_name }}={{ docker_binary_target_version }}"
        state: present
        allow_downgrade: true
      register: docker_binary_install_result
      when: docker_binary_version_change_required

  always:
    - name: Binary | Put '{{ docker_binary_dpkg_name }}' into hold
      ansible.builtin.dpkg_selections:
        name: "{{ docker_binary_dpkg_name }}"
        selection: hold
      when:
        - put_docker_dpkg_into_hold
        - docker_binary_version_change_required or (not docker_binary_currently_held)
        - (docker_binary_installed
          or (docker_binary_install_result is defined
          and docker_binary_install_result is succeeded
          and docker_binary_install_result is not skipped))

- name: Binary | Get '{{ lookup('vars', item ~ '_name') }}' version
  ansible.builtin.command:
    argv: "{{ ['docker', 'compose', 'version']
           if item == 'compose_cli'
           else [lookup('vars', item ~ '_filepath'), '--version'] }}"
  register: binary_version_command
  ignore_errors: true
  changed_when: false

- name: Binary | Parse '{{ lookup('vars', item ~ '_name') }}' version
  ansible.builtin.set_fact:
    binary_version: "{{ (binary_version_command.stdout_lines | first | default('')).split()[3 if item == 'compose_cli' else 2]
                        | default('')
                        | regex_replace(',$', '')
                        | regex_replace('^v', '') }}"

- name: Binary | Display '{{ lookup('vars', item ~ '_name') }}' version
  ansible.builtin.debug:
    msg: "{{ lookup('vars', item ~ '_name') }} version {{ binary_version }} {{ 'installed'
                                                                            if (docker_binary_install_result is defined and docker_binary_install_result is changed)
                                                                            else 'unchanged' }}."
  when: (binary_version is defined)
