#########################################################################
# Title:         Saltbox: Hetzner | GRUB Edit Tasks                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: GRUB Edits | Set parameters to remove
  ansible.builtin.set_fact:
    grub_item_to_remove:
      - "nomodeset"

- name: GRUB Edits | Get default kernel parameters
  ansible.builtin.slurp:
    src: "{{ outer_item.item }}"
  register: grub_defaults_content

- name: GRUB Edits | Set default kernel parameters
  ansible.builtin.set_fact:
    grub_default_kernel_parameters: "{{ (grub_defaults_content.content
                                         | b64decode
                                         | regex_findall('(?m)^GRUB_CMDLINE_LINUX_DEFAULT\\s*=\\s*\"([^\"]*)\"')
                                         | first
                                         | default('')).split() }}"

- name: GRUB Edits | Set final kernel parameters
  ansible.builtin.set_fact:
    grub_final_kernel_parameters: "{{ grub_default_kernel_parameters | reject('in', grub_item_to_remove) | list }}"

- name: GRUB Edits | Update 'GRUB_CMDLINE_LINUX_DEFAULT'
  ansible.builtin.replace:
    path: "{{ outer_item.item }}"
    regexp: '(^GRUB_CMDLINE_LINUX_DEFAULT\s?=.*)'
    replace: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ grub_final_kernel_parameters | join(' ') }}\""
  register: x

- name: GRUB Edits | Reload GRUB
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  register: grub_register_update
  failed_when: ('error' in grub_register_update.stderr)
  when: (x is changed)

- name: GRUB Edits | Set 'reboot_is_necessary' variable
  ansible.builtin.set_fact:
    reboot_is_necessary: true
  when: (x is changed)
