##########################################################################
# Title:         Saltbox: Authelia | File Backend Task                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: File | Check if 'users_database.yml' exists
  ansible.builtin.stat:
    path: "{{ lookup('role_var', '_paths_location', role='authelia') }}/users_database.yml"
  register: authelia_user_config_stat

- name: File | Import default 'configuration.yml'
  ansible.builtin.template:
    src: configuration.yml.j2
    dest: "{{ lookup('role_var', '_paths_location', role='authelia') }}/configuration.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
  when: (not authelia_config_stat.stat.exists)

- name: File | Format 'configuration.yml'
  ansible.builtin.command:
    argv:
      - "yyq"
      - "-i"
      - "{{ lookup('role_var', '_paths_location', role='authelia') }}/configuration.yml"
  when: (not authelia_config_stat.stat.exists)

- name: File | Generate Password Hash
  community.docker.docker_container:
    name: authelia-password-hash
    image: "{{ lookup('role_var', '_docker_image') }}"
    command: "authelia crypto hash generate --config /config/configuration.yml --password {{ user.pass | quote }}"
    detach: false
    volumes:
      - "{{ lookup('role_var', '_paths_location', role='authelia') }}:/config"
    networks:
      - name: saltbox
    cleanup: true
    state: started
    container_default_behavior: compatibility
    tls_hostname: localhost
    pull: true
  register: authelia_password_generate
  no_log: true
  when: (not authelia_user_config_stat.stat.exists)

- name: File | Extract Password Hash Matches
  ansible.builtin.set_fact:
    authelia_password_hash_matches: "{{ authelia_password_generate.container.Output
                                        | regex_findall('(?m)^Digest: (.*)$') }}"
  no_log: true
  when: (not authelia_user_config_stat.stat.exists)

- name: File | Validate Password Hash
  ansible.builtin.assert:
    that:
      - authelia_password_hash_matches | length == 1
  no_log: true
  when: (not authelia_user_config_stat.stat.exists)

- name: File | Store Password Hash
  ansible.builtin.set_fact:
    authelia_password_hash: "{{ authelia_password_hash_matches | first | trim }}"
  no_log: true
  when: (not authelia_user_config_stat.stat.exists)

- name: File | Import default 'users_database.yml'
  ansible.builtin.template:
    src: users_database.yml.j2
    dest: "{{ lookup('role_var', '_paths_location', role='authelia') }}/users_database.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
  no_log: true
  when: (not authelia_user_config_stat.stat.exists)

- name: File | Remove LLDAP Container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "lldap"
