#########################################################################
# Title:         Saltbox: Traefik | Crowdsec Task                       #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check if Traefik Crowdsec bouncer key file exists
  ansible.builtin.stat:
    path: "{{ crowdsec_bouncer_traefik_path }}"
  register: traefik_crowdsec_bouncer_traefik_path_stat

- name: Fail if Traefik Crowdsec bouncer key file does not exist
  ansible.builtin.fail:
    msg: "Crowdsec enabled but not yet installed. Run crowdsec install first."
  when: not traefik_crowdsec_bouncer_traefik_path_stat.stat.exists

- name: Load existing bouncer key
  ansible.builtin.slurp:
    src: "{{ crowdsec_bouncer_traefik_path }}"
  register: crowdsec_bouncer_traefik_key

- name: Load Crowdsec port value
  ansible.builtin.slurp:
    src: /etc/crowdsec/config.yaml
  register: crowdsec_config_content

- name: Parse Crowdsec listen URI
  ansible.builtin.set_fact:
    crowdsec_listen_uri: "{{ (crowdsec_config_content.content | b64decode | from_yaml).api.server.listen_uri | default('') }}"

- name: Validate Crowdsec listen URI
  ansible.builtin.assert:
    that:
      - crowdsec_listen_uri is string
      - crowdsec_listen_uri | trim | length > 0
      - (crowdsec_listen_uri | regex_search(':[0-9]+$')) is not none

- name: Parse Crowdsec port value
  ansible.builtin.set_fact:
    crowdsec_port_value: "{{ crowdsec_listen_uri | regex_findall('([0-9]+)$') | first }}"

- name: Set facts
  ansible.builtin.set_fact:
    traefik_crowdsec_bouncer_key: "{{ crowdsec_bouncer_traefik_key['content'] | b64decode }}"
    traefik_crowdsec_port: "{{ crowdsec_port_value }}"

- name: Import ban html file
  ansible.builtin.copy:
    src: "ban.html"
    force: true
    dest: "{{ lookup('role_var', '_paths_location', role='traefik') }}/ban.html"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
