#########################################################################
# Title:         Saltbox: Docker | BTRFS | Cleanup Tasks                #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# https://gist.github.com/hopeseekr/cd2058e71d01deca5bae9f4e5a555440

- name: BTRFS | Cleanup | Check to see if '/var/lib/docker/' exists
  ansible.builtin.stat:
    path: "/var/lib/docker/"
  register: var_lib_docker

- name: BTRFS | Cleanup | Tasks when '/var/lib/docker' exists
  when: var_lib_docker.stat.exists
  block:
    - name: BTRFS | Cleanup | Check filesystem of '/var/lib/docker' path
      ansible.builtin.command:
        argv:
          - "stat"
          - "-f"
          - "-c"
          - "%T"
          - "/var/lib/docker"
      register: var_lib_docker_file_system

    - name: BTRFS | Cleanup | Tasks when '/var/lib/docker' is btrfs
      when: ('btrfs' in var_lib_docker_file_system.stdout)
      block:
        - name: BTRFS | Cleanup | Query all Docker container IDs
          ansible.builtin.command:
            argv:
              - "docker"
              - "ps"
              - "-aq"
          register: docker_btrfs_container_ids_before_stop
          changed_when: false
          failed_when: false

        - name: BTRFS | Cleanup | Stop all Docker containers
          ansible.builtin.command:
            argv: "{{ ['docker', 'container', 'stop'] + docker_btrfs_container_ids_before_stop.stdout_lines }}"
          failed_when: false
          when: (docker_btrfs_container_ids_before_stop.stdout_lines | length > 0)

        - name: BTRFS | Cleanup | Re-query all Docker container IDs
          ansible.builtin.command:
            argv:
              - "docker"
              - "ps"
              - "-aq"
          register: docker_btrfs_container_ids_before_remove
          changed_when: false
          failed_when: false

        - name: BTRFS | Cleanup | Remove all Docker containers
          ansible.builtin.command:
            argv: "{{ ['docker', 'container', 'rm'] + docker_btrfs_container_ids_before_remove.stdout_lines }}"
          failed_when: false
          when: (docker_btrfs_container_ids_before_remove.stdout_lines | length > 0)

        - name: BTRFS | Cleanup | Query all Docker image IDs
          ansible.builtin.command:
            argv:
              - "docker"
              - "images"
              - "-q"
          register: docker_btrfs_image_ids
          changed_when: false
          failed_when: false

        - name: BTRFS | Cleanup | Force-remove all Docker images
          ansible.builtin.command:
            argv: "{{ ['docker', 'image', 'rm', '-f'] + docker_btrfs_image_ids.stdout_lines }}"
          failed_when: false
          when: (docker_btrfs_image_ids.stdout_lines | length > 0)

        - name: BTRFS | Cleanup | Prune Docker images
          community.docker.docker_prune:
            images: true
            images_filters:
              dangling: false
          ignore_errors: true

        - name: BTRFS | Cleanup | Query all Docker volume names
          ansible.builtin.command:
            argv:
              - "docker"
              - "volume"
              - "ls"
              - "-q"
          register: docker_btrfs_volume_names
          changed_when: false
          failed_when: false

        - name: BTRFS | Cleanup | Remove all Docker volumes
          ansible.builtin.command:
            argv: "{{ ['docker', 'volume', 'rm'] + docker_btrfs_volume_names.stdout_lines }}"
          failed_when: false
          when: (docker_btrfs_volume_names.stdout_lines | length > 0)

        - name: BTRFS | Cleanup | Prune Docker volumes
          community.docker.docker_prune:
            volumes: true
          ignore_errors: true

        - name: BTRFS | Cleanup | Stop docker service
          ansible.builtin.systemd_service:
            name: docker
            state: stopped

        - name: BTRFS | Cleanup | Stop docker socket
          ansible.builtin.systemd_service:
            name: docker.socket
            state: stopped

        - name: BTRFS | Cleanup | Wait for 30 seconds before commencing
          ansible.builtin.wait_for:
            timeout: 30

        - name: BTRFS | Cleanup | Find '/var/lib/docker' btrfs subvolumes
          ansible.builtin.find:
            paths: "/var/lib/docker/btrfs/subvolumes"
            file_type: directory
            hidden: true
            recurse: false
          register: docker_btrfs_subvolumes
          ignore_errors: true

        - name: BTRFS | Cleanup | Remove '/var/lib/docker' btrfs subvolumes
          ansible.builtin.command:
            argv:
              - "btrfs"
              - "subvolume"
              - "delete"
              - "{{ docker_btrfs_subvolume.path }}"
          loop: "{{ docker_btrfs_subvolumes.files | default([]) | sort(attribute='path') }}"
          loop_control:
            loop_var: docker_btrfs_subvolume
          failed_when: false

        - name: BTRFS | Cleanup | Remove '/var/lib/docker' path
          ansible.builtin.file:
            path: "/var/lib/docker"
            state: absent
